# Generated by Django 5.2.7 on 2025-12-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=12),
        ),
    ]
