# Generated by Django 5.2.7 on 2025-11-23 22:02

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=projects.models.default_due_date),
        ),
    ]
