# Generated by Django 5.2.7 on 2025-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
