# Generated by Django 5.2.7 on 2025-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_time_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.AddField(
            model_name='project',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
