"""added more models and updated users

Revision ID: 20c507f06c11
Revises: 7f672475f231
Create Date: 2026-07-28 01:55:21.061453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c507f06c11'
down_revision: Union[str, Sequence[str], None] = '7f672475f231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('requires_approval', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'clients', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'requires_approval')
    # ### end Alembic commands ###
