"""add invoice_items table, drop time_entries.invoice_id

Revision ID: 649c7109147f
Revises: 941702c162fa
Create Date: 2026-08-12 21:04:56.548567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649c7109147f'
down_revision: Union[str, Sequence[str], None] = '941702c162fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invoice_items',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('invoice_id', sa.UUID(), nullable=False),
        sa.Column('time_entry_id', sa.UUID(), nullable=True),
        sa.Column('milestone_id', sa.UUID(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=13, scale=2), nullable=False),
        sa.Column('amount', sa.Numeric(precision=13, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_invoice_items_invoice_id_invoices', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name='fk_invoice_items_time_entry_id_time_entries', ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='fk_invoice_items_milestone_id_milestones', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_constraint(op.f('fk_time_entries_invoice_id_invoices'), 'time_entries', type_='foreignkey')
    op.drop_column('time_entries', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_time_entries_invoice_id_invoices'), 'time_entries', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    op.drop_table('invoice_items')
    # ### end Alembic commands ###
