"""added unique contraint to freelancer_id and email in clients table

Revision ID: 7f672475f231
Revises: aa5996767027
Create Date: 2026-07-19 16:38:08.692435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f672475f231'
down_revision: Union[str, Sequence[str], None] = 'aa5996767027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_client_freelancer_email', 'clients', ['freelancer_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_freelancer_email', 'clients', type_='unique')
    # ### end Alembic commands ###
