"""add invoice payment methods

Revision ID: 8748d1b38480
Revises: c6340f65ae02
Create Date: 2026-10-07 22:27:49.004926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.sensitive
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8748d1b38480'
down_revision: Union[str, Sequence[str], None] = 'c6340f65ae02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('PAYONEER', 'ESFCA_WIRE', 'ELEVATE_PAY', 'WISE_TO_IBAN', 'PKR_BANK_TRANSFER', 'RAAST', 'JAZZCASH', 'EASYPAISA', 'BANK_TRANSFER', 'OTHER', name='paymentmethodtype', create_type=False), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('details', app.core.sensitive.EncryptedText(), nullable=False),
    sa.Column('source_method_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_method_id'], ['payment_method_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payment_methods_invoice_id'), 'invoice_payment_methods', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_payment_methods_invoice_id'), table_name='invoice_payment_methods')
    op.drop_table('invoice_payment_methods')
    # ### end Alembic commands ###
