"""add invoices table, time_entries.invoice_id, restrict invoice fk deletes

Revision ID: 941702c162fa
Revises: 20c507f06c11
Create Date: 2026-08-11 02:35:43.113278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941702c162fa'
down_revision: Union[str, Sequence[str], None] = '20c507f06c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELEED', name='invoicestatus'), nullable=False),
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=13, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=13, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.add_column('time_entries', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_time_entries_invoice_id_invoices', 'time_entries', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_time_entries_invoice_id_invoices', 'time_entries', type_='foreignkey')
    op.drop_column('time_entries', 'invoice_id')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
