"""add payment method configs

Revision ID: c6340f65ae02
Revises: 7d2f4b6a9c10
Create Date: 2026-10-05 18:43:02.456984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.sensitive


# revision identifiers, used by Alembic.
revision: str = 'c6340f65ae02'
down_revision: Union[str, Sequence[str], None] = '7d2f4b6a9c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PAYONEER', 'ESFCA_WIRE', 'ELEVATE_PAY', 'WISE_TO_IBAN', 'PKR_BANK_TRANSFER', 'RAAST', 'JAZZCASH', 'EASYPAISA', 'BANK_TRANSFER', 'OTHER', name='paymentmethodtype'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('details', app.core.sensitive.EncryptedText(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_methods_freelancer_order', 'payment_method_configs', ['freelancer_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_methods_freelancer_order', table_name='payment_method_configs')
    op.drop_table('payment_method_configs')
    sa.Enum(name='paymentmethodtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
